/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as DatasetsSlugRouteImport } from './routes/datasets.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSlugRoute = DatasetsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DatasetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/research': typeof ResearchRoute
  '/datasets/$slug': typeof DatasetsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/research': typeof ResearchRoute
  '/datasets/$slug': typeof DatasetsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/research': typeof ResearchRoute
  '/datasets/$slug': typeof DatasetsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/datasets' | '/developers' | '/research' | '/datasets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/datasets' | '/developers' | '/research' | '/datasets/$slug'
  id:
    | '__root__'
    | '/'
    | '/datasets'
    | '/developers'
    | '/research'
    | '/datasets/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsRoute: typeof DatasetsRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$slug': {
      id: '/datasets/$slug'
      path: '/$slug'
      fullPath: '/datasets/$slug'
      preLoaderRoute: typeof DatasetsSlugRouteImport
      parentRoute: typeof DatasetsRoute
    }
  }
}

interface DatasetsRouteChildren {
  DatasetsSlugRoute: typeof DatasetsSlugRoute
}

const DatasetsRouteChildren: DatasetsRouteChildren = {
  DatasetsSlugRoute: DatasetsSlugRoute,
}

const DatasetsRouteWithChildren = DatasetsRoute._addFileChildren(
  DatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
