/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as DatasetsIndexRouteImport } from './routes/datasets.index'
import { Route as DatasetsSlugRouteImport } from './routes/datasets.$slug'
import { Route as AuthenticatedSubmissionsIndexRouteImport } from './routes/_authenticated/submissions.index'
import { Route as AuthenticatedSubmissionsIdRouteImport } from './routes/_authenticated/submissions.$id'
import { Route as AuthenticatedSubmissionsNewRouteImport } from './routes/_authenticated/submissions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsSlugRoute = DatasetsSlugRouteImport.update({
  id: '/datasets/$slug',
  path: '/datasets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmissionsIndexRoute =
  AuthenticatedSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsIdRoute =
  AuthenticatedSubmissionsIdRouteImport.update({
    id: '/submissions/$id',
    path: '/submissions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubmissionsNewRoute =
  AuthenticatedSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/research': typeof ResearchRoute
  '/datasets/$slug': typeof DatasetsSlugRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/submissions/': typeof AuthenticatedSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/research': typeof ResearchRoute
  '/datasets/$slug': typeof DatasetsSlugRoute
  '/datasets': typeof DatasetsIndexRoute
  '/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/submissions': typeof AuthenticatedSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/research': typeof ResearchRoute
  '/datasets/$slug': typeof DatasetsSlugRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/_authenticated/submissions/$id': typeof AuthenticatedSubmissionsIdRoute
  '/_authenticated/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/_authenticated/submissions/': typeof AuthenticatedSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/developers'
    | '/research'
    | '/datasets/$slug'
    | '/datasets/'
    | '/submissions/$id'
    | '/submissions/new'
    | '/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/developers'
    | '/research'
    | '/datasets/$slug'
    | '/datasets'
    | '/submissions/$id'
    | '/submissions/new'
    | '/submissions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/developers'
    | '/research'
    | '/datasets/$slug'
    | '/datasets/'
    | '/_authenticated/submissions/$id'
    | '/_authenticated/submissions/new'
    | '/_authenticated/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DevelopersRoute: typeof DevelopersRoute
  ResearchRoute: typeof ResearchRoute
  DatasetsSlugRoute: typeof DatasetsSlugRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$slug': {
      id: '/datasets/$slug'
      path: '/datasets/$slug'
      fullPath: '/datasets/$slug'
      preLoaderRoute: typeof DatasetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submissions/': {
      id: '/_authenticated/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthenticatedSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/$id': {
      id: '/_authenticated/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthenticatedSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions/new': {
      id: '/_authenticated/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof AuthenticatedSubmissionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSubmissionsIdRoute: typeof AuthenticatedSubmissionsIdRoute
  AuthenticatedSubmissionsNewRoute: typeof AuthenticatedSubmissionsNewRoute
  AuthenticatedSubmissionsIndexRoute: typeof AuthenticatedSubmissionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSubmissionsIdRoute: AuthenticatedSubmissionsIdRoute,
  AuthenticatedSubmissionsNewRoute: AuthenticatedSubmissionsNewRoute,
  AuthenticatedSubmissionsIndexRoute: AuthenticatedSubmissionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DevelopersRoute: DevelopersRoute,
  ResearchRoute: ResearchRoute,
  DatasetsSlugRoute: DatasetsSlugRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
